
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinearInterpolationCalculator(object):
    def setupUi(self, LinearInterpolationCalculator):
        LinearInterpolationCalculator.setObjectName("LinearInterpolationCalculator")
        LinearInterpolationCalculator.resize(800, 600)
        LinearInterpolationCalculator.setStyleSheet("QMainWindow {background-color: gray}")
        self.centralwidget = QtWidgets.QWidget(LinearInterpolationCalculator)
        self.centralwidget.setObjectName("centralwidget")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {color:rgb(255, 170, 0)}")
        self.label_2.setObjectName("label_2")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(350, 220, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("x")
        self.label_6.setText("x = ")
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(560, 220, 381, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("y")
        self.label_7.setText("y = ")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 170, 261, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(8)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)

        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)

        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(420, 120, 500, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 60, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 200, 351, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 120, 150, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 280, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("QPushButton {background-color: rgb(250, 50, 10); color: rgb(250, 250, 250)}")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 280, 101, 23))
        self.pushButton_3.setStyleSheet("QPushButton {background-color: rgb(250, 50, 10); color: rgb(250, 250, 250)}")

        self.pushButton_3.setObjectName("pushButton_3")
        # self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        # self.tableWidget_2.setGeometry(QtCore.QRect(340, 170, 171, 191))

        # self.tableWidget_2.setObjectName("tableWidget_2")
        # self.tableWidget_2.setColumnCount(1)
        # self.tableWidget_2.setRowCount(5)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_2.setVerticalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_2.setVerticalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_2.setVerticalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_2.setVerticalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget_2.setVerticalHeaderItem(4, item)
        # item = QtWidgets.QTableWidgetItem()
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # font.setBold(True)
        # font.setWeight(75)
        # item.setFont(font)
        # self.tableWidget_2.setHorizontalHeaderItem(0, item)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(382, 230, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(592, 230, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 310, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(600, 310, 120, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        LinearInterpolationCalculator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LinearInterpolationCalculator)
        self.statusbar.setObjectName("statusbar")
        LinearInterpolationCalculator.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(LinearInterpolationCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 782, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("QMenuBar {color: rgb(0, 0, 0)}")
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        LinearInterpolationCalculator.setMenuBar(self.menubar)
        self.actionFull_Screen = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionMinimize = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionMaximize = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionNew = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionNew.setShortcutVisibleInContextMenu(False)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionHelp.setObjectName("actionHelp")
        self.actionPreferences = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMenu = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionMenu.setObjectName("actionMenu")
        self.actionUndo = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo_2 = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionUndo_2.setObjectName("actionUndo_2")
        self.actionRedo_2 = QtWidgets.QAction(LinearInterpolationCalculator)
        self.actionRedo_2.setObjectName("actionRedo_2")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionUndo_2)
        self.menuEdit.addAction(self.actionRedo_2)
        self.menuView.addAction(self.actionMenu)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuWindow.addAction(self.actionFull_Screen)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionMaximize)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(LinearInterpolationCalculator)
        QtCore.QMetaObject.connectSlotsByName(LinearInterpolationCalculator)

        self.pushButton_2.clicked.connect(self.solve_x)
        self.pushButton_3.clicked.connect(self.solve_y)



    def retranslateUi(self, LinearInterpolationCalculator):
        _translate = QtCore.QCoreApplication.translate
        LinearInterpolationCalculator.setWindowTitle(_translate("LinearInterpolationCalculator", "MainWindow"))
        self.label_2.setText(_translate("LinearInterpolationCalculator", "Numerical Methods Calculator"))

        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("LinearInterpolationCalculator", "Summation_x1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("LinearInterpolationCalculator", "Summation_y1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("LinearInterpolationCalculator", "Summation_x1^2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("LinearInterpolationCalculator", "Summation_xy"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("LinearInterpolationCalculator", "Mean_x1"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("LinearInterpolationCalculator", "Mean_y1"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("LinearInterpolationCalculator", "a0"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("LinearInterpolationCalculator", "a1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("LinearInterpolationCalculator", "Value"))

        self.label.setText(_translate("LinearInterpolationCalculator", "y = a1x + a0 + e"))
        self.label_3.setText(_translate("LinearInterpolationCalculator", "Linear Regression Analysis "))
        self.pushButton.setText(_translate("LinearInterpolationCalculator", "Linear Interpolatotion Calculator"))
        self.pushButton_2.setText(_translate("LinearInterpolationCalculator", "Solve for x"))
        self.pushButton_3.setText(_translate("LinearInterpolationCalculator", "Solve for y"))
        self.pushButton_4.setText(_translate("LinearInterpolationCalculator", "General Equation"))
        self.label_4.setText(_translate("LinearInterpolationCalculator", "y = "))
        self.label_5.setText(_translate("LinearInterpolationCalculator", "x = "))
        self.menuFile.setTitle(_translate("LinearInterpolationCalculator", "File"))
        self.menuEdit.setTitle(_translate("LinearInterpolationCalculator", "Edit"))
        self.menuView.setTitle(_translate("LinearInterpolationCalculator", "View"))
        self.menuSettings.setTitle(_translate("LinearInterpolationCalculator", "Settings"))
        self.menuWindow.setTitle(_translate("LinearInterpolationCalculator", "Window "))
        self.menuHelp.setTitle(_translate("LinearInterpolationCalculator", "Help"))
        self.actionFull_Screen.setText(_translate("LinearInterpolationCalculator", "Full Screen"))
        self.actionFull_Screen.setShortcut(_translate("LinearInterpolationCalculator", "F11"))
        self.actionMinimize.setText(_translate("LinearInterpolationCalculator", "Minimize"))
        self.actionMinimize.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+N"))
        self.actionMaximize.setText(_translate("LinearInterpolationCalculator", "Maximize"))
        self.actionMaximize.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+M"))
        self.actionNew.setText(_translate("LinearInterpolationCalculator", "New"))
        self.actionNew.setStatusTip(_translate("LinearInterpolationCalculator", "Create a new file"))
        self.actionNew.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+N"))
        self.actionOpen.setText(_translate("LinearInterpolationCalculator", "Open"))
        self.actionOpen.setStatusTip(_translate("LinearInterpolationCalculator", "Open a file"))
        self.actionSave.setText(_translate("LinearInterpolationCalculator", "Save"))
        self.actionSave.setStatusTip(_translate("LinearInterpolationCalculator", "Save a file"))
        self.actionSave.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+S"))
        self.actionSave_As.setText(_translate("LinearInterpolationCalculator", "Save As"))
        self.actionSave_As.setStatusTip(_translate("LinearInterpolationCalculator", "Save as a new file"))
        self.actionClose.setText(_translate("LinearInterpolationCalculator", "Close"))
        self.actionExit.setText(_translate("LinearInterpolationCalculator", "Exit"))
        self.actionAbout.setText(_translate("LinearInterpolationCalculator", "About"))
        self.actionAbout.setShortcut(_translate("LinearInterpolationCalculator", "F12"))
        self.actionHelp.setText(_translate("LinearInterpolationCalculator", "Help"))
        self.actionHelp.setShortcut(_translate("LinearInterpolationCalculator", "F1"))
        self.actionPreferences.setText(_translate("LinearInterpolationCalculator", "Preferences"))
        self.actionPreferences.setShortcut(_translate("LinearInterpolationCalculator", "F10"))
        self.actionMenu.setText(_translate("LinearInterpolationCalculator", "Menu"))
        self.actionMenu.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+M"))
        self.actionUndo.setText(_translate("LinearInterpolationCalculator", "History"))
        self.actionUndo.setStatusTip(_translate("LinearInterpolationCalculator", "Check History"))
        self.actionUndo.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+H"))
        self.actionRedo.setText(_translate("LinearInterpolationCalculator", "Copy"))
        self.actionRedo.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+C"))
        self.actionCut.setText(_translate("LinearInterpolationCalculator", "Cut"))
        self.actionCut.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+X"))
        self.actionPaste.setText(_translate("LinearInterpolationCalculator", "Paste"))
        self.actionUndo_2.setText(_translate("LinearInterpolationCalculator", "Undo"))
        self.actionUndo_2.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+Z"))
        self.actionRedo_2.setText(_translate("LinearInterpolationCalculator", "Redo"))
        self.actionRedo_2.setShortcut(_translate("LinearInterpolationCalculator", "Ctrl+R"))

    def populate(self, data):
        self.data = data

        self.tableWidget.setItem(-1, 1, QtWidgets.QTableWidgetItem(str(self.data['totalx'])))
        self.tableWidget.setItem(0, 1, QtWidgets.QTableWidgetItem(str(self.data['totaly'])))
        self.tableWidget.setItem(1, 1, QtWidgets.QTableWidgetItem(str(self.data['totalx2'])))
        self.tableWidget.setItem(2, 1, QtWidgets.QTableWidgetItem(str(self.data['totalxy'])))
        self.tableWidget.setItem(3, 1, QtWidgets.QTableWidgetItem(str(self.data['mean_x'])))
        self.tableWidget.setItem(4, 1, QtWidgets.QTableWidgetItem(str(self.data['mean_y'])))
        self.tableWidget.setItem(5, 1, QtWidgets.QTableWidgetItem(str(self.data['a0'])))
        self.tableWidget.setItem(6, 1, QtWidgets.QTableWidgetItem(str(self.data['a1'])))

    def equation_changed(self):
        a0 = self.data['a0']
        a1 = self.data['a1']
        self.label.setText(f'y = {a0} + {a1}x')

    def solve_x(self):
        a0 = self.data['a0']
        a1 = self.data['a1']

        y_input = self.lineEdit_2.text()
        y1 = float(y_input)
        x = round((y1 - a0) / a1, 4)
        self.label_5.setText(f'x = {x}')

    def solve_y(self):
        a0 = self.data['a0']
        a1 = self.data['a1']

        x_input = self.lineEdit.text()
        x1 = float(x_input)
        y = round(a1 * x1 + a0, 4)
        self.label_4.setText(f'y = {y}')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LinearInterpolationCalculator = QtWidgets.QMainWindow()
    ui = Ui_LinearInterpolationCalculator()
    ui.setupUi(LinearInterpolationCalculator)
    LinearInterpolationCalculator.show()
    sys.exit(app.exec_())
