
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from input_table_pr import Ui_InputDataPR


class Ui_PolynomialRegressionAnalysis(object):
    def setupUi(self, PolynomialRegressionAnalysis):
        PolynomialRegressionAnalysis.setObjectName("PolynomialRegressionAnalysis")
        PolynomialRegressionAnalysis.resize(800, 600)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        PolynomialRegressionAnalysis.setFont(font)
        PolynomialRegressionAnalysis.setStyleSheet("QMainWindow{\n"
"    background-color: gray;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(PolynomialRegressionAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 130, 211, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 60, 300, 60))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("QLabel {\n"
"    color:rgb(255, 170, 0)}")
        self.label.setMidLineWidth(0)
        self.label.setObjectName("label")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 370, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 170, 0)\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 140, 401, 131))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QWidget {\n"
"    color: rgb(255, 255, 255)\n"
"}")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 310, 90, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border-color:red\n"
"}")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        PolynomialRegressionAnalysis.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PolynomialRegressionAnalysis)
        self.statusbar.setObjectName("statusbar")
        PolynomialRegressionAnalysis.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(PolynomialRegressionAnalysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 781, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        PolynomialRegressionAnalysis.setMenuBar(self.menubar)
        self.actionFull_Screen = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionMinimize = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionMinimize.setObjectName("actionMinimize")
        self.actionMaximize = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionMaximize.setObjectName("actionMaximize")
        self.actionNew = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionNew.setShortcutVisibleInContextMenu(False)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionHelp.setObjectName("actionHelp")
        self.actionPreferences = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionMenu = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionMenu.setObjectName("actionMenu")
        self.actionUndo = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo_2 = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionUndo_2.setObjectName("actionUndo_2")
        self.actionRedo_2 = QtWidgets.QAction(PolynomialRegressionAnalysis)
        self.actionRedo_2.setObjectName("actionRedo_2")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionUndo_2)
        self.menuEdit.addAction(self.actionRedo_2)
        self.menuView.addAction(self.actionMenu)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuWindow.addAction(self.actionFull_Screen)
        self.menuWindow.addAction(self.actionMinimize)
        self.menuWindow.addAction(self.actionMaximize)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PolynomialRegressionAnalysis)
        QtCore.QMetaObject.connectSlotsByName(PolynomialRegressionAnalysis)

        self.pushButton_3.clicked.connect(self.switch_to_pr)

    def retranslateUi(self, PolynomialRegressionAnalysis):
        _translate = QtCore.QCoreApplication.translate
        PolynomialRegressionAnalysis.setWindowTitle(_translate("PolynomialRegressionAnalysis", "Polynomial Regression"))
        self.pushButton.setText(_translate("PolynomialRegressionAnalysis", "Polynomial Regression Analysis"))
        self.label.setText(_translate("PolynomialRegressionAnalysis", "  Curve Fitting"))
        self.pushButton_3.setText(_translate("PolynomialRegressionAnalysis", "Generate "))
        self.label_2.setText(_translate("PolynomialRegressionAnalysis", "Enter the number of pairs of data"))
        self.menuFile.setTitle(_translate("PolynomialRegressionAnalysis", "File"))
        self.menuEdit.setTitle(_translate("PolynomialRegressionAnalysis", "Edit"))
        self.menuView.setTitle(_translate("PolynomialRegressionAnalysis", "View"))
        self.menuSettings.setTitle(_translate("PolynomialRegressionAnalysis", "Settings"))
        self.menuWindow.setTitle(_translate("PolynomialRegressionAnalysis", "Window "))
        self.menuHelp.setTitle(_translate("PolynomialRegressionAnalysis", "Help"))
        self.actionFull_Screen.setText(_translate("PolynomialRegressionAnalysis", "Full Screen"))
        self.actionFull_Screen.setShortcut(_translate("PolynomialRegressionAnalysis", "F11"))
        self.actionMinimize.setText(_translate("PolynomialRegressionAnalysis", "Minimize"))
        self.actionMinimize.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+N"))
        self.actionMaximize.setText(_translate("PolynomialRegressionAnalysis", "Maximize"))
        self.actionMaximize.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+M"))
        self.actionNew.setText(_translate("PolynomialRegressionAnalysis", "New"))
        self.actionNew.setStatusTip(_translate("PolynomialRegressionAnalysis", "Create a new file"))
        self.actionNew.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+N"))
        self.actionOpen.setText(_translate("PolynomialRegressionAnalysis", "Open"))
        self.actionOpen.setStatusTip(_translate("PolynomialRegressionAnalysis", "Open a file"))
        self.actionSave.setText(_translate("PolynomialRegressionAnalysis", "Save"))
        self.actionSave.setStatusTip(_translate("PolynomialRegressionAnalysis", "Save a file"))
        self.actionSave.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+S"))
        self.actionSave_As.setText(_translate("PolynomialRegressionAnalysis", "Save As"))
        self.actionSave_As.setStatusTip(_translate("PolynomialRegressionAnalysis", "Save as a new file"))
        self.actionClose.setText(_translate("PolynomialRegressionAnalysis", "Close"))
        self.actionExit.setText(_translate("PolynomialRegressionAnalysis", "Exit"))
        self.actionAbout.setText(_translate("PolynomialRegressionAnalysis", "About"))
        self.actionAbout.setShortcut(_translate("PolynomialRegressionAnalysis", "F12"))
        self.actionHelp.setText(_translate("PolynomialRegressionAnalysis", "Help"))
        self.actionHelp.setShortcut(_translate("PolynomialRegressionAnalysis", "F1"))
        self.actionPreferences.setText(_translate("PolynomialRegressionAnalysis", "Preferences"))
        self.actionPreferences.setShortcut(_translate("PolynomialRegressionAnalysis", "F10"))
        self.actionMenu.setText(_translate("PolynomialRegressionAnalysis", "Menu"))
        self.actionMenu.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+M"))
        self.actionUndo.setText(_translate("PolynomialRegressionAnalysis", "History"))
        self.actionUndo.setStatusTip(_translate("PolynomialRegressionAnalysis", "Check History"))
        self.actionUndo.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+H"))
        self.actionRedo.setText(_translate("PolynomialRegressionAnalysis", "Copy"))
        self.actionRedo.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+C"))
        self.actionCut.setText(_translate("PolynomialRegressionAnalysis", "Cut"))
        self.actionCut.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+X"))
        self.actionPaste.setText(_translate("PolynomialRegressionAnalysis", "Paste"))
        self.actionUndo_2.setText(_translate("PolynomialRegressionAnalysis", "Undo"))
        self.actionUndo_2.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+Z"))
        self.actionRedo_2.setText(_translate("PolynomialRegressionAnalysis", "Redo"))
        self.actionRedo_2.setShortcut(_translate("PolynomialRegressionAnalysis", "Ctrl+R"))

    def switch_to_pr(self):
        try:
            cc = (self.lineEdit.text())
            column_count = int(round(float(cc)))
            self.window = QtWidgets.QWidget()
            self.ui = Ui_InputDataPR()
            self.ui.setupUi(self.window)
            self.window.show()
            self.ui.tableWidget.setColumnCount(column_count)
        except ValueError:
            cc = (self.lineEdit.setText(""))
            self.error_messageBox()
            print("Please enter an integer!")

    def error_messageBox(self):
        msg = QMessageBox()
        msg.setWindowTitle("Input Error")
        msg.setText("Please input an Integer")
        msg.setIcon(QMessageBox.Warning)
        msg.setStandardButtons(QMessageBox.Retry)
        x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PolynomialRegressionAnalysis = QtWidgets.QMainWindow()
    ui = Ui_PolynomialRegressionAnalysis()
    ui.setupUi(PolynomialRegressionAnalysis)
    PolynomialRegressionAnalysis.show()
    sys.exit(app.exec_())
